[package]
name = "replay-normalize"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
indexer-finalize = { workspace = true }
indexer-types = { workspace = true }
replay-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
